#!/bin/bash

echo -n " disp: "
case `xbacklight -get | cut -b 1,2,3` in
    [0-9].*)  echo "▮      " ;;
    1[0-9].) echo "▮▯     " ;;
    2[0-9].) echo "▮▮     " ;; 
    3[0-9].) echo "▮▮▯    " ;; 
    4[0-9].) echo "▮▮▮    " ;;
    5[0-9].) echo "▮▮▮▯   " ;;
    6[0-9].) echo "▮▮▮▮   " ;;
    7[0-9].) echo "▮▮▮▮▯  " ;;
    8[0-9].) echo "▮▮▮▮▮  " ;;
    9[0-9].) echo "▮▮▮▮▮▯ " ;;
    100) echo "▮▮▮▮▮▮ " ;;
esac

