#!/bin/sh

bspc monitor DVI-D-0 -d one two three four five six
bspc monitor DP-4 -d un deux trois quatre cinq six


desktop_config() {
    bspc config $1 $2
    for M in $(bspc query -M); do
        bspc config -m $M $1 $2
    done
}


desktop_config border_width        5

bspc config window_gap 20

bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     false

bspc config top_padding 17px
bspc config presel_feedback_color "#ffe1cb"
bspc config normal_border_color "#4f5c7c"
bspc config focused_border_color "#ffe1cb"
bspc config focus_follows_pointer true
