#! /bin/sh

bspc monitor -d 1 2 3 4 5 

bspc config border_width        5
bspc config window_gap          5
bspc config split_ratio         0.52
bspc config borderless_monocle  false
bspc config gapless_monocle     false

bspc config top_padding 17px
bspc config presel_border_color "#ff6565"
bspc config normal_border_color "#212121"
bspc config focused_border_color "#afafaf"
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop=^3 follow=on floating=on
bspc rule -a pavucontrol floating=on focus=on
bspc rule -a feh floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
