#!/bin/bash

echo -n " vol: "
case `amixer | grep "Front Left: "| sed -n 2p | awk '{print $4}' | sed -r 's/\[//g' | sed -r 's/\]//g' | sed -r 's/%//g'` in
    0)  echo "muted  " ;;
    [1-9])  echo "▮      " ;;
    1[0-9]) echo "▮▯     " ;;
    2[0-9]) echo "▮▮     " ;; 
    3[0-9]) echo "▮▮▯    " ;; 
    4[0-9]) echo "▮▮▮    " ;;
    5[0-9]) echo "▮▮▮▯   " ;;
    6[0-9]) echo "▮▮▮▮   " ;;
    7[0-9]) echo "▮▮▮▮▯  " ;;
    8[0-9]) echo "▮▮▮▮▮  " ;;
    9[0-9]) echo "▮▮▮▮▮▯ " ;;
    100) echo "▮▮▮▮▮▮ " ;;
esac


