#!/bin/bash

E="%{F#151721}"
Z="%{F-}"

while read -r line; do
echo -n " $E"
    case `bspc query -D -d | awk '{print substr($0,length,1)}'` in
        "5")
			echo -n "$Z››$E ⬤ ⬤ ⬤ ";;
		"6")
			echo -n "›› $Z⬤$E ⬤ ⬤ ";;
		"7")
			echo -n "›› ⬤ $Z⬤$E ⬤ ";;
		"8")
			echo -n "›› ⬤ ⬤ $Z⬤$E ";;
	esac
echo "$Z"
done < <(bspc subscribe report)
