#!/bin/env zsh

. "/home/james/.cache/wal/colors.sh"

# Misc
HEIGHT="30"
sep="»"
PAD=" "

# Colors
BG="%{F$background}"
PRIMARY="%{F$color4}"
SECONDARY="%{F$color6}"
OFF="%{B-}%{F-}"

# Positioning
LEFT="%{l}"
CENTER="%{c}"
RIGHT="%{r}"

# FIFO
PANEL_FIFO="/tmp/PANEL_FIFO"
