#!/bin/bash

# Misc
sep=">"
PAD=" "

# Colors
MAGENTA="%{F#8a89aa}"
LMAGENTA="%{F#b2b1dc}"
BLUE="%{F#5888a9}"
DYELLOW="%{F#ab9e7f}"
YELLOW="%{F#aa8d57}"
LYELLOW="%{F#dcb670}"
CYAN="%{F#859ca9}"
LCYAN="%{F#accadb}"
OFF="%{B-}%{F-}"

# Positioning
LEFT="%{l}"
CENTER="%{c}"
RIGHT="%{r}"

# FIFO
PANEL_FIFO="/tmp/PANEL_FIFO"
